<?php

namespace Drupal\shopnew\Form\cart;

use Drupal\Core\Form\FormStateInterface;
use Drupal\shopnew\Form\FormWebBase;
use Drupal\shopnew\Helper\SessionHelper;

class ListForm extends FormWebBase
{
  function getFormId()
  {
    // TODO: Implement getFormId() method.
    return 'shop_new_cart_form_list';
  }

  function buildForm(array $form , FormStateInterface $form_state)
  {
    $session = SessionHelper::getSession();
    // TODO: Implement buildForm() method.
  }

  function validateForm(array &$form , FormStateInterface $form_state)
  {
    parent::validateForm($form , $form_state); // TODO: Change the autogenerated stub
  }

  function submitForm(array &$form , FormStateInterface $form_state)
  {
    // TODO: Implement submitForm() method.
  }
}
