<?php
/**
 * Created by PhpStorm.
 * User: dell
 * Date: 9/20/2018
 * Time: 12:16 AM
 */

namespace Drupal\shopnew\Form;

use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;


class SettingsForm extends ConfigFormBase
{
  function __construct(ConfigFactoryInterface $config_factory)
  {
    parent::__construct($config_factory);
  }

  public static function create(ContainerInterface $container)
  {
    return new static(
      $container->get('config.factory')
    );
  }

  protected function getEditableConfigNames()
  {
    return [
      'shopnew.settings',
    ];
  }

  public function getFormId()
  {
    return 'shopnew_admin_settings_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state, Request $request = NULL)
  {

    return parent::buildForm($form, $form_state);
  }

  function submitForm(array &$form, FormStateInterface $form_state)
  {
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}
